### ISSUE TITLE
analysis_driver can not be found

### ISSUE THREAD

**Issue by Tyler799** [snl-dakota/dakota#116]
I am trying to run Dakota 6.19 on Windows. 

Unfortunately, I can't get Dakota to run the interface script I set up:

```
interface
	id_interface = 'MY_INTERFACE'

		fork   
		analysis_driver = 'my_interface_script.bat'
		parameters_file = 'params.in'
		results_file = 'results.out'
		file_tag
		work_directory directory_tag named 'workdir'
	  	copy_files = 'templatedir/*'
		#file_save directory_save
```

When it gets to this point, standard error reports:

`Could not spawn; error code 2 (No such file or directory)`

And the standard output reports:

`blocking fork: my_interface_script.bat params.in.1 results.out.1`

So clearly Dakota can't find my interface script. I've tried removing the file extension from analysis_driver as well in case it's picky about that - I know it doesn't like that being a path instead of a filename.

I'm not sure what to do. Nothing in the documentation seems to cover what to do in this case. There's no mention of 'blocking fork' or 'could not spawn' anywhere.

**Comment by Tyler799** [comment]
Update: fork seems to be the problem. If I switch it to the deprecated "system" option, it works flawlessly.

**Comment by iaae** [comment]
Dakota may have less mileage on Windows and less Q&A. Here is what I have found:
Dakota with .BAT driver on Windows only works with system(). If you switch to .EXE/.COM, it will work properly and "blocking" the process correctly till it finishes the process (system() won't allow such sync properly...rely solely on Dakota monitoring of response file creation).

If you try to set any input command/file to Dakota, it does take path info. You will need to set up as "drive:\\\\dirrectory\\\\filename"...note the "\\\\", or
"drive:/directiry/filename"

I have reported a bug that these filenames cannot exceed 32 bytes...have not had time to review the source code for confirmation and no developers responded yet.

Hope these help.

**Comment by iaae** [comment]
BTW, in the above backsplash pathname, if it is used inside Dakota input file, you will need to use "drive:\\\\path\\\\fname", and an additional quote pair if you have blank spaces in your path/filename.

**Comment by briadam** [comment]
If memory serves, with fork on Windows, the specified analysis driver must be a valid executable (not script) that can start executing when the Dakota process is forked/spawned to start the analysis driver. (In contrast to system calls, where the subprocess will start the appropriate/registered interpreter on your behalf.)

So when using fork, I've often found the need to specify the analysis driver similar to:
`cmd.exe analysis_driver = 'my_interface_script.bat'`
that way the command interpreter gets forked and interprets the bat script. You may find you need to give command-line switches to cmd.exe to get the behavior you want (as I'm a little rusty on this).

**Comment by Tyler799** [comment]
If you are correct Briadam, I would highly suggest someone update the Docs to reflect this:

https://snl-dakota.github.io/docs/6.19.0/users/usingdakota/reference/interface-analysis_drivers.html

**Comment by Tyler799** [comment]
> cmd.exe analysis_driver = 'my_interface_script.bat'

Are you sure about that format? If I put cmd.exe before analysis_driver, I get an error:

`Input line 299: unrecognized identifier 'cmd.exe'.`

**Comment by briadam** [comment]
Nope, not sure at all. Corrected above to `analysis_driver = 'cmd.exe my_interface_script.bat'` The idea is you want Dakota to fork the cmd.exe process and pass it the argument script.bat so cmd will interpret the batch script.

**Comment by Tyler799** [comment]
> Nope, not sure at all. ;-) Corrected above to `analysis_driver = 'cmd.exe my_interface_script.bat'` The idea is you want Dakota to fork the cmd.exe process and pass it the argument script.bat so cmd will interpret the batch script.

Well, no error occurs - but Dakota is unable to finish. It gets to this point and then just stops:

`blocking fork: cmd.exe FLIP_interface_script.bat params.in.1 results.out.1`

There's nothing in the error log, which is unusual.

**Comment by Tyler799** [comment]
> cmd.exe env does not auto-exit after BAT... your BAT may want to have an "exit" cmd.

I've tried both exit and exit /b (leaves the parent window/script/calling label open) and both don't work.

**Comment by iaae** [comment]
Unfortunately, we don't use BAT as it is fairly insecure so not much more suggestions. You can see our post about using an EXE driver and communicating with the SIM solver using RCP or dynamic loaded DLL. You should be able to write an exe/com driver serving all BAT commands, receive param input and execute SIM for the result/response, then exit properly for Dakota to continue the optimization process iterations.  Hope these help.

**Comment by Tyler799** [comment]
> Unfortunately, we don't use BAT as it is fairly insecure so not much more suggestions. You can see our post about using an EXE driver and communicating with the SIM solver using RCP or dynamic loaded DLL. You should be able to write an exe/com driver serving all BAT commands, receive param input and execute SIM for the result/response, then exit properly for Dakota to continue the optimization process iterations. Hope these help.

I'm afraid I don't really follow.

So my best bet is re-writing what was done in the batch script in another language, like C/C++, compiling that into an executable, and then using that? :(

I'm don't know what you mean by SIM solver or RCP, or why a DLL would be needed.

**Comment by iaae** [comment]
after adding cmd shell, have you switched back to fork yet?
The reason we use remote /interprocess call is because we are driving the optimization process from the top level UI so the user don't know any optimization process.  You don't have to worry about that if you just want to replace BAT with a simple EXE. I think there are open source EXE code that can serve as or take BAT commands.

**Comment by Tyler799** [comment]
> after adding cmd shell, have you switched back to fork yet?

Yes. analysis_driver = 'cmd.exe my_interface_script.bat' with `fork` doesn't work for me - it just gets to this in the log and then stops:

`blocking fork: cmd.exe my_interface_script.bat params.in.1 results.out.1`

Nothing in the error log.

I can still use system without CMD and it runs fine, but it doesn't seem to play nice with async.

**Comment by iaae** [comment]
I think you follow this: dakota\share\dakota\examples\official\drivers\windows_bat
Note that it uses system() and relies on result file generation detection...not very reliable (it uses file_save rather than your file_tag)

The time you spend on the BAT may be just enough to write an EXE driver.  I think Dakota uses process exit HANDLE on fork to detect the driver exit, and it is a more secure standard process monitoring.

**Comment by Tyler799** [comment]
Closing this issue, as Fork does not play nice with batch scripts. Only recommendation for change is that the Dakota documentation really should reflect this limitation. I've moved on to a Fork + Executable approach which works great.
